import './globals.css'
import IBMPlex from 'next/font/local'
import MaterialSymbols from 'next/font/local'
import { headers } from "next/headers"
import ColorContextProvider from './context/colorContext'
import SiteHeader from './components/site-header'
import SiteFooter from './components/site-footer'
import { getCurrentPage } from './sanity/sanity.query'

const ibmplex = IBMPlex({ 
    src: '/fonts/IBM_Plex_Sans_Var-Roman.woff2',
    subsets: ['latin'],
    variable: '--font-ibmplex',
})

const materialSymbols = MaterialSymbols({ 
    src: '/fonts/MaterialSymbolsSharp[FILL,GRAD,opsz,wght].woff2',
    style: 'normal',
    variable: '--font-symbols',
    display: 'block',
})

export const metadata = {
    title: 'Next-Sanity Showcase',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    const headersList = headers()
    const pathname = headersList.get('x-url') || ""
    const isStudioRoute = pathname.startsWith('/studio')

    const data = await getCurrentPage(pathname)
    const theme = data?.pageColors.themeselector || null

    if (isStudioRoute) { return <html lang="en"><body>{children}</body></html> }

    return (
        <html lang="en" className={`font-light`} suppressHydrationWarning>
            <body className={`${ibmplex.variable} font-sans ${materialSymbols.variable}`}>
                <ColorContextProvider>
                        <SiteHeader />
                            <main className='main min-h-screen w-full '>
                                {children}
                            </main>
                        <SiteFooter />
                </ColorContextProvider>
            </body>
        </html>
    )
}