import './globals.css'
import IBMPlex from 'next/font/local'
import { headers } from "next/headers"
import PageContextProvider from './context/PageContext'
import SiteHeader from './components/SiteHeader'
import SiteFooter from './components/SiteFooter'
import { getPage } from './sanity/sanity.query'

const ibmplex = IBMPlex({ 
    src: '/fonts/IBM_Plex_Sans_Var-Roman.woff2',
    subsets: ['latin'],
    variable: '--font-ibmplex',
})

// const materialSymbols = MaterialSymbols({ 
//     src: '/fonts/MaterialSymbolsSharp[FILL,GRAD,opsz,wght].woff2',
//     style: 'normal',
//     variable: '--font-symbols',
//     display: 'block',
// })

export const metadata = {
    title: 'Next-Sanity Showcase',
    description: 'Generated by create next app',
}

export default async function RootLayout({ children }) {
    const headersList = headers()
    const pathname = headersList.get('x-url') || ""
    const isStudioRoute = pathname.startsWith('/studio')
    const serverCurrentPage = await getPage(pathname)
    
    if (isStudioRoute) { return <html lang="en"><body>{children}</body></html> }

    return (
        <html lang="en" className={`font-light`} suppressHydrationWarning>
            <body className={`${ibmplex.variable} font-sans`}>
                <PageContextProvider serverCurrentPage={serverCurrentPage}>
                        <SiteHeader />
                            <main className='main min-h-screen w-full'>
                                {children}
                            </main>
                        <SiteFooter />
                </PageContextProvider>
            </body>
        </html>
    )
}